// Second half of the mission catalogue: historic flagships, the Mars surface
// fleet, the heliophysics fleet, Earth observation and commercial lunar flights.
// Same rules as missions.ts: dates and results come from NASA mission pages and
// the NSSDC master catalogue, nothing estimated.
import type { MissionProfile } from "./missions";

const sci = (slug: string) => `https://science.nasa.gov/mission/${slug}/`;

export const EXTRA_MISSIONS: MissionProfile[] = [
  // ----------------------------- Human spaceflight -----------------------
  {
    id: "apollo-11",
    name: "Apollo 11",
    agency: "NASA",
    status: "completed",
    category: "lunar",
    launched: "1969-07-16",
    launchLabel: "16 July 1969",
    vehicle: "Saturn V",
    destination: "Moon, Sea of Tranquility",
    objective: "Perform a crewed lunar landing and return the crew safely to Earth.",
    highlights: [
      "Neil Armstrong and Buzz Aldrin landed on 20 July 1969 while Michael Collins orbited in Columbia.",
      "Returned about 21.5 kg of lunar samples.",
      "Splashed down in the Pacific on 24 July 1969.",
    ],
    milestones: [
      { date: "1969-07-20", label: "Lunar module Eagle lands at Tranquility Base" },
    ],
    url: "https://www.nasa.gov/mission/apollo-11/",
    ended: "1969-07-24",
  },
  {
    id: "apollo-13",
    name: "Apollo 13",
    agency: "NASA",
    status: "completed",
    category: "lunar",
    launched: "1970-04-11",
    launchLabel: "11 April 1970",
    vehicle: "Saturn V",
    destination: "Free-return trajectory around the Moon",
    objective: "Planned third lunar landing, aborted after an oxygen tank failure in the service module.",
    highlights: [
      "An oxygen tank ruptured on 13 April 1970, about 56 hours into the flight.",
      "The crew used the lunar module Aquarius as a lifeboat around the Moon.",
      "Jim Lovell, Jack Swigert and Fred Haise splashed down safely on 17 April 1970.",
    ],
    url: "https://www.nasa.gov/mission/apollo-13/",
    ended: "1970-04-17",
  },
  {
    id: "apollo-17",
    name: "Apollo 17",
    agency: "NASA",
    status: "completed",
    category: "lunar",
    launched: "1972-12-07",
    launchLabel: "7 December 1972",
    vehicle: "Saturn V",
    destination: "Moon, Taurus-Littrow valley",
    objective: "The final Apollo landing, focused on extended geology with a trained geologist on the crew.",
    highlights: [
      "Eugene Cernan and Harrison Schmitt spent about 75 hours on the surface.",
      "Returned about 110 kg of samples, the largest Apollo haul.",
      "The last time humans walked on the Moon.",
    ],
    url: "https://www.nasa.gov/mission/apollo-17/",
    ended: "1972-12-19",
  },
  {
    id: "skylab",
    name: "Skylab",
    agency: "NASA",
    status: "completed",
    category: "human",
    launched: "1973-05-14",
    launchLabel: "14 May 1973",
    vehicle: "Saturn V (modified two-stage)",
    destination: "Low Earth orbit",
    objective: "The first US space station, for solar astronomy, Earth observation and long-duration human physiology.",
    highlights: [
      "Hosted three crews between 1973 and 1974.",
      "The final crew stayed 84 days, a US record at the time.",
      "Re-entered the atmosphere on 11 July 1979.",
    ],
    url: "https://www.nasa.gov/skylab/",
    ended: "1979-07-11",
  },
  {
    id: "space-shuttle",
    name: "Space Shuttle Program",
    agency: "NASA",
    status: "completed",
    category: "human",
    launched: "1981-04-12",
    launchLabel: "12 April 1981 (STS-1)",
    vehicle: "Space Shuttle orbiters",
    destination: "Low Earth orbit",
    objective: "A partially reusable crewed launch system for satellites, laboratories and space station assembly.",
    highlights: [
      "135 missions flown by five orbiters.",
      "Launched the Hubble Space Telescope and assembled most of the ISS.",
      "Final landing, STS-135 Atlantis, on 21 July 2011.",
    ],
    url: "https://www.nasa.gov/space-shuttle/",
    ended: "2011-07-21",
  },
  {
    id: "commercial-crew",
    name: "Commercial Crew Program",
    agency: "NASA with SpaceX and Boeing",
    status: "active",
    category: "human",
    launched: "2020-05-30",
    launchLabel: "30 May 2020 (Demo-2)",
    vehicle: "Falcon 9 with Crew Dragon",
    destination: "International Space Station",
    objective: "Fly NASA astronauts to the ISS on commercially owned and operated spacecraft.",
    highlights: [
      "Demo-2 restored crewed launches from US soil for the first time since 2011.",
      "Crew rotation flights to the ISS have run on Crew Dragon since Crew-1 in November 2020.",
    ],
    url: "https://www.nasa.gov/humans-in-space/commercial-space/commercial-crew-program/",
    internal: { label: "Track the station live", to: "/tracker" },
  },
  {
    id: "im-1",
    name: "Intuitive Machines IM-1 (CLPS)",
    agency: "NASA CLPS with Intuitive Machines",
    status: "completed",
    category: "lunar",
    launched: "2024-02-15",
    launchLabel: "15 February 2024",
    vehicle: "Falcon 9",
    destination: "Moon, south polar region near Malapert A",
    objective: "Deliver NASA science payloads to the lunar surface on a commercial lander, Odysseus.",
    highlights: [
      "Landed on 22 February 2024, the first US soft landing on the Moon since 1972.",
      "The lander came to rest tilted but returned data from NASA instruments.",
    ],
    url: "https://www.nasa.gov/commercial-lunar-payload-services/",
    ended: "2024-02-29",
  },
  {
    id: "blue-ghost-1",
    name: "Blue Ghost Mission 1 (CLPS)",
    agency: "NASA CLPS with Firefly Aerospace",
    status: "completed",
    category: "lunar",
    launched: "2025-01-15",
    launchLabel: "15 January 2025",
    vehicle: "Falcon 9",
    destination: "Moon, Mare Crisium",
    objective: "Carry ten NASA science and technology payloads to the Moon on a commercial lander.",
    highlights: [
      "Landed upright on 2 March 2025, the first fully successful commercial lunar landing.",
      "Operated through a full lunar day and recorded a sunset from the surface.",
    ],
    url: "https://www.nasa.gov/commercial-lunar-payload-services/",
    ended: "2025-03-16",
  },

  // ----------------------------- Mars ------------------------------------
  {
    id: "viking-1",
    name: "Viking 1",
    agency: "NASA",
    status: "completed",
    category: "planetary",
    launched: "1975-08-20",
    launchLabel: "20 August 1975",
    vehicle: "Titan IIIE Centaur",
    destination: "Mars, Chryse Planitia",
    objective: "Image Mars from orbit and the surface and search for evidence of life.",
    highlights: [
      "Landed on 20 July 1976, the first successful US Mars landing.",
      "Carried biology experiments that tested soil samples for metabolism.",
      "Lander operated until November 1982.",
    ],
    url: sci("viking-1"),
    ended: "1982-11-13",
    internal: { label: "Open the Mars page", to: "/mars" },
  },
  {
    id: "viking-2",
    name: "Viking 2",
    agency: "NASA",
    status: "completed",
    category: "planetary",
    launched: "1975-09-09",
    launchLabel: "9 September 1975",
    vehicle: "Titan IIIE Centaur",
    destination: "Mars, Utopia Planitia",
    objective: "A second orbiter and lander pair, extending Viking 1's surface science to the northern plains.",
    highlights: [
      "Landed on 3 September 1976.",
      "Photographed frost on the surface during the Martian winter.",
    ],
    url: sci("viking-2"),
    ended: "1980-04-11",
  },
  {
    id: "mars-pathfinder",
    name: "Mars Pathfinder",
    agency: "NASA JPL",
    status: "completed",
    category: "planetary",
    launched: "1996-12-04",
    launchLabel: "4 December 1996",
    vehicle: "Delta II",
    destination: "Mars, Ares Vallis",
    objective: "Demonstrate a low-cost airbag landing and deploy Sojourner, the first rover on another planet.",
    highlights: [
      "Landed on 4 July 1997 using airbags.",
      "Sojourner analysed rocks and soil around the landing site.",
      "Last contact on 27 September 1997.",
    ],
    url: sci("mars-pathfinder"),
    ended: "1997-09-27",
  },
  {
    id: "mars-odyssey",
    name: "2001 Mars Odyssey",
    agency: "NASA JPL",
    status: "extended",
    category: "planetary",
    launched: "2001-04-07",
    launchLabel: "7 April 2001",
    vehicle: "Delta II",
    destination: "Mars orbit",
    objective: "Map Martian surface composition and detect buried water ice.",
    highlights: [
      "Found large amounts of hydrogen near the poles, pointing to subsurface ice.",
      "The longest-serving spacecraft at Mars and a relay for surface missions.",
    ],
    url: sci("mars-odyssey"),
    internal: { label: "Open the Mars page", to: "/mars" },
  },
  {
    id: "spirit",
    name: "Spirit (Mars Exploration Rover A)",
    agency: "NASA JPL",
    status: "completed",
    category: "planetary",
    launched: "2003-06-10",
    launchLabel: "10 June 2003",
    vehicle: "Delta II",
    destination: "Mars, Gusev Crater",
    objective: "Search rocks and soils for evidence of past water activity.",
    highlights: [
      "Landed on 4 January 2004 for a planned 90-sol mission.",
      "Found silica-rich soil pointing to past hot springs or steam vents.",
      "Became stuck in soft soil in 2009; last contact in March 2010.",
    ],
    url: sci("mars-exploration-rovers-spirit-and-opportunity"),
    ended: "2011-05-25",
    internal: { label: "Browse Mars imagery", to: "/mars" },
  },
  {
    id: "opportunity",
    name: "Opportunity (Mars Exploration Rover B)",
    agency: "NASA JPL",
    status: "completed",
    category: "planetary",
    launched: "2003-07-07",
    launchLabel: "7 July 2003",
    vehicle: "Delta II Heavy",
    destination: "Mars, Meridiani Planum",
    objective: "Search rocks and soils for evidence of past water activity.",
    highlights: [
      "Landed on 25 January 2004 and worked for nearly 15 years.",
      "Drove more than 45 km, a record for off-world driving at the time.",
      "Fell silent during a planet-wide dust storm in June 2018.",
    ],
    url: sci("mars-exploration-rovers-spirit-and-opportunity"),
    ended: "2019-02-13",
    internal: { label: "Browse Mars imagery", to: "/mars" },
  },
  {
    id: "phoenix",
    name: "Phoenix Mars Lander",
    agency: "NASA JPL with University of Arizona",
    status: "completed",
    category: "planetary",
    launched: "2007-08-04",
    launchLabel: "4 August 2007",
    vehicle: "Delta II",
    destination: "Mars, northern arctic plains",
    objective: "Dig into the arctic soil to study water ice and habitability.",
    highlights: [
      "Landed on 25 May 2008.",
      "Confirmed water ice just below the surface.",
      "Detected perchlorate in the soil.",
    ],
    url: sci("phoenix"),
    ended: "2008-11-02",
  },
  {
    id: "insight",
    name: "InSight",
    agency: "NASA JPL",
    status: "completed",
    category: "planetary",
    launched: "2018-05-05",
    launchLabel: "5 May 2018",
    vehicle: "Atlas V 401",
    destination: "Mars, Elysium Planitia",
    objective: "Study the deep interior of Mars with a seismometer and heat probe.",
    highlights: [
      "Landed on 26 November 2018.",
      "Recorded more than 1,300 marsquakes.",
      "Measured the size of the Martian core and crust.",
    ],
    url: sci("insight"),
    ended: "2022-12-21",
  },
  {
    id: "ingenuity",
    name: "Ingenuity Mars Helicopter",
    agency: "NASA JPL",
    status: "completed",
    category: "planetary",
    launched: "2020-07-30",
    launchLabel: "30 July 2020 (with Perseverance)",
    vehicle: "Atlas V 541",
    destination: "Mars, Jezero Crater",
    objective: "Demonstrate powered, controlled flight on another planet.",
    highlights: [
      "First flight on 19 April 2021.",
      "Completed 72 flights against a planned five.",
      "Mission ended in January 2024 after rotor blade damage.",
    ],
    url: sci("mars-2020-perseverance/ingenuity-mars-helicopter"),
    ended: "2024-01-25",
    internal: { label: "Browse Mars imagery", to: "/mars" },
  },

  // ----------------------------- Outer planets & small bodies -------------
  {
    id: "pioneer-10",
    name: "Pioneer 10",
    agency: "NASA Ames",
    status: "completed",
    category: "planetary",
    launched: "1972-03-03",
    launchLabel: "3 March 1972",
    vehicle: "Atlas-Centaur",
    destination: "Jupiter, then interstellar space",
    objective: "Cross the asteroid belt and make the first flyby of Jupiter.",
    highlights: [
      "First spacecraft through the asteroid belt.",
      "Flew past Jupiter on 3 December 1973.",
      "Last signal received on 23 January 2003.",
    ],
    url: sci("pioneer-10"),
    ended: "2003-01-23",
  },
  {
    id: "pioneer-11",
    name: "Pioneer 11",
    agency: "NASA Ames",
    status: "completed",
    category: "planetary",
    launched: "1973-04-06",
    launchLabel: "6 April 1973",
    vehicle: "Atlas-Centaur",
    destination: "Jupiter and Saturn",
    objective: "Fly past Jupiter and make the first flyby of Saturn.",
    highlights: [
      "Flew past Jupiter in December 1974.",
      "First spacecraft to fly past Saturn, on 1 September 1979.",
    ],
    url: sci("pioneer-11"),
    ended: "1995-09-30",
  },
  {
    id: "galileo",
    name: "Galileo",
    agency: "NASA JPL",
    status: "completed",
    category: "planetary",
    launched: "1989-10-18",
    launchLabel: "18 October 1989",
    vehicle: "Space Shuttle Atlantis (STS-34) with IUS",
    destination: "Jupiter orbit",
    objective: "Orbit Jupiter and drop a probe into its atmosphere.",
    highlights: [
      "Entered Jupiter orbit on 7 December 1995 and released an atmospheric probe.",
      "Found strong evidence of a salty ocean beneath Europa's ice.",
      "Deliberately sent into Jupiter on 21 September 2003 to protect Europa.",
    ],
    url: sci("galileo"),
    ended: "2003-09-21",
  },
  {
    id: "dawn",
    name: "Dawn",
    agency: "NASA JPL",
    status: "completed",
    category: "planetary",
    launched: "2007-09-27",
    launchLabel: "27 September 2007",
    vehicle: "Delta II Heavy",
    destination: "Asteroid Vesta and dwarf planet Ceres",
    objective: "Orbit the two largest bodies in the main asteroid belt using ion propulsion.",
    highlights: [
      "Orbited Vesta from 2011 to 2012, then Ceres from 2015.",
      "First spacecraft to orbit two different bodies beyond Earth and the Moon.",
      "Found bright salt deposits in Ceres' Occator Crater.",
    ],
    url: sci("dawn"),
    ended: "2018-11-01",
  },
  {
    id: "dart",
    name: "DART",
    agency: "NASA with Johns Hopkins APL",
    status: "completed",
    category: "planetary",
    launched: "2021-11-24",
    launchLabel: "24 November 2021",
    vehicle: "Falcon 9",
    destination: "Asteroid Dimorphos",
    objective: "Test whether a kinetic impact can change an asteroid's orbit, for planetary defence.",
    highlights: [
      "Struck Dimorphos on 26 September 2022.",
      "Shortened Dimorphos' orbit around Didymos by about 32 minutes.",
    ],
    url: sci("dart"),
    ended: "2022-09-26",
    internal: { label: "Open Asteroid Watch", to: "/neo" },
  },
  {
    id: "stardust",
    name: "Stardust",
    agency: "NASA JPL",
    status: "completed",
    category: "planetary",
    launched: "1999-02-07",
    launchLabel: "7 February 1999",
    vehicle: "Delta II",
    destination: "Comet Wild 2",
    objective: "Collect dust from a comet's coma and return it to Earth.",
    highlights: [
      "Flew through the coma of comet Wild 2 in January 2004.",
      "Sample capsule landed in Utah on 15 January 2006.",
      "Later flew past comet Tempel 1 as Stardust-NExT.",
    ],
    url: sci("stardust"),
    ended: "2011-03-24",
  },
  {
    id: "deep-impact",
    name: "Deep Impact",
    agency: "NASA JPL",
    status: "completed",
    category: "planetary",
    launched: "2005-01-12",
    launchLabel: "12 January 2005",
    vehicle: "Delta II",
    destination: "Comet Tempel 1",
    objective: "Fire an impactor into a comet to expose its interior.",
    highlights: [
      "The impactor hit Tempel 1 on 4 July 2005.",
      "Later flew past comet Hartley 2 as the EPOXI mission.",
      "Contact was lost in August 2013.",
    ],
    url: sci("deep-impact-epoxi"),
    ended: "2013-09-20",
  },

  // ----------------------------- Inner planets ---------------------------
  {
    id: "messenger",
    name: "MESSENGER",
    agency: "NASA with Johns Hopkins APL",
    status: "completed",
    category: "planetary",
    launched: "2004-08-03",
    launchLabel: "3 August 2004",
    vehicle: "Delta II",
    destination: "Mercury orbit",
    objective: "The first spacecraft to orbit Mercury, mapping its surface, composition and magnetic field.",
    highlights: [
      "Entered Mercury orbit on 18 March 2011.",
      "Found water ice in permanently shadowed polar craters.",
      "Ended with a planned impact on 30 April 2015.",
    ],
    url: sci("messenger"),
    ended: "2015-04-30",
  },
  {
    id: "magellan",
    name: "Magellan",
    agency: "NASA JPL",
    status: "completed",
    category: "planetary",
    launched: "1989-05-04",
    launchLabel: "4 May 1989",
    vehicle: "Space Shuttle Atlantis (STS-30) with IUS",
    destination: "Venus orbit",
    objective: "Map the surface of Venus through its clouds with radar.",
    highlights: [
      "Entered Venus orbit on 10 August 1990.",
      "Mapped about 98 percent of the surface by radar.",
      "Ended with a planned plunge into the atmosphere in October 1994.",
    ],
    url: sci("magellan"),
    ended: "1994-10-13",
  },

  // ----------------------------- Astrophysics ----------------------------
  {
    id: "cgro",
    name: "Compton Gamma Ray Observatory",
    agency: "NASA Goddard",
    status: "completed",
    category: "astrophysics",
    launched: "1991-04-05",
    launchLabel: "5 April 1991",
    vehicle: "Space Shuttle Atlantis (STS-37)",
    destination: "Low Earth orbit",
    objective: "The second of NASA's Great Observatories, surveying the sky in gamma rays.",
    highlights: [
      "Showed gamma-ray bursts are spread evenly across the sky, pointing to distant origins.",
      "Deorbited in a controlled re-entry on 4 June 2000.",
    ],
    url: "https://heasarc.gsfc.nasa.gov/docs/cgro/",
    ended: "2000-06-04",
  },
  {
    id: "cobe",
    name: "COBE",
    agency: "NASA Goddard",
    status: "completed",
    category: "astrophysics",
    launched: "1989-11-18",
    launchLabel: "18 November 1989",
    vehicle: "Delta",
    destination: "Sun-synchronous Earth orbit",
    objective: "Measure the cosmic microwave background left over from the early universe.",
    highlights: [
      "Showed the background radiation matches a near-perfect blackbody spectrum.",
      "Detected tiny temperature variations, recognised by the 2006 Nobel Prize in Physics.",
    ],
    url: "https://lambda.gsfc.nasa.gov/product/cobe/",
    ended: "1993-12-23",
  },
  {
    id: "wmap",
    name: "WMAP",
    agency: "NASA Goddard",
    status: "completed",
    category: "astrophysics",
    launched: "2001-06-30",
    launchLabel: "30 June 2001",
    vehicle: "Delta II",
    destination: "Sun-Earth L2",
    objective: "Map the cosmic microwave background across the full sky in fine detail.",
    highlights: [
      "Pinned down the age of the universe at about 13.77 billion years.",
      "Ended science operations in August 2010.",
    ],
    url: "https://map.gsfc.nasa.gov/",
    ended: "2010-08-20",
  },
  {
    id: "nustar",
    name: "NuSTAR",
    agency: "NASA JPL with Caltech",
    status: "extended",
    category: "astrophysics",
    launched: "2012-06-13",
    launchLabel: "13 June 2012",
    vehicle: "Pegasus XL",
    destination: "Low Earth orbit",
    objective: "The first orbiting telescope to focus high-energy X-rays.",
    highlights: [
      "Studies black holes, supernova remnants and neutron stars.",
      "Uses a 10 m deployable mast to separate its optics and detectors.",
    ],
    url: sci("nustar"),
  },
  {
    id: "spherex",
    name: "SPHEREx",
    agency: "NASA JPL",
    status: "active",
    category: "astrophysics",
    launched: "2025-03-11",
    launchLabel: "11 March 2025",
    vehicle: "Falcon 9",
    destination: "Sun-synchronous Earth orbit",
    objective: "Map the entire sky in 102 infrared colours to study cosmic inflation, galaxies and interstellar ice.",
    highlights: [
      "Launched together with NASA's PUNCH heliophysics mission.",
      "Builds a full-sky spectral map roughly every six months.",
    ],
    url: sci("spherex"),
  },
  {
    id: "euclid",
    name: "Euclid",
    agency: "ESA with NASA contribution",
    status: "active",
    category: "astrophysics",
    launched: "2023-07-01",
    launchLabel: "1 July 2023",
    vehicle: "Falcon 9",
    destination: "Sun-Earth L2",
    objective: "Map billions of galaxies to study dark matter and dark energy.",
    highlights: [
      "NASA supplied the near-infrared detectors.",
      "Surveying about a third of the sky over six years.",
    ],
    url: "https://www.esa.int/Science_Exploration/Space_Science/Euclid",
  },

  // ----------------------------- Heliophysics ----------------------------
  {
    id: "stereo",
    name: "STEREO",
    agency: "NASA Goddard",
    status: "extended",
    category: "heliophysics",
    launched: "2006-10-26",
    launchLabel: "26 October 2006",
    vehicle: "Delta II",
    destination: "Heliocentric orbit near Earth's",
    objective: "Twin spacecraft giving stereoscopic views of the Sun and coronal mass ejections.",
    highlights: [
      "In 2011 the pair and SDO saw the whole Sun at once for the first time.",
      "Contact with STEREO-B was lost in 2014; STEREO-A continues.",
    ],
    url: sci("stereo"),
    internal: { label: "Open Space Weather", to: "/weather" },
  },
  {
    id: "mms",
    name: "Magnetospheric Multiscale (MMS)",
    agency: "NASA Goddard",
    status: "extended",
    category: "heliophysics",
    launched: "2015-03-13",
    launchLabel: "13 March 2015",
    vehicle: "Atlas V 421",
    destination: "Highly elliptical Earth orbit",
    objective: "Four spacecraft flying in formation to study magnetic reconnection.",
    highlights: [
      "Made the first direct observations of magnetic reconnection in space.",
      "Held the record for the highest-altitude GPS fix.",
    ],
    url: sci("mms"),
  },
  {
    id: "themis",
    name: "THEMIS",
    agency: "NASA with UC Berkeley",
    status: "extended",
    category: "heliophysics",
    launched: "2007-02-17",
    launchLabel: "17 February 2007",
    vehicle: "Delta II",
    destination: "Earth orbit, with two probes later sent to the Moon as ARTEMIS",
    objective: "Five probes studying what triggers substorms that brighten auroras.",
    highlights: [
      "Showed magnetic reconnection triggers substorm onset.",
      "Two probes were moved into lunar orbit in 2011.",
    ],
    url: sci("themis"),
  },
  {
    id: "ibex",
    name: "IBEX",
    agency: "NASA with Southwest Research Institute",
    status: "extended",
    category: "heliophysics",
    launched: "2008-10-19",
    launchLabel: "19 October 2008",
    vehicle: "Pegasus XL",
    destination: "High Earth orbit",
    objective: "Map the boundary of the heliosphere using energetic neutral atoms.",
    highlights: [
      "Discovered a ribbon of neutral atom emission at the edge of the heliosphere.",
    ],
    url: sci("ibex"),
  },
  {
    id: "wind",
    name: "Wind",
    agency: "NASA Goddard",
    status: "extended",
    category: "heliophysics",
    launched: "1994-11-01",
    launchLabel: "1 November 1994",
    vehicle: "Delta II",
    destination: "Sun-Earth L1",
    objective: "Measure the solar wind before it reaches Earth's magnetosphere.",
    highlights: ["One of the longest-running heliophysics missions still in operation."],
    url: sci("wind"),
    internal: { label: "Open Space Weather", to: "/weather" },
  },
  {
    id: "ace",
    name: "Advanced Composition Explorer (ACE)",
    agency: "NASA",
    status: "extended",
    category: "heliophysics",
    launched: "1997-08-25",
    launchLabel: "25 August 1997",
    vehicle: "Delta II",
    destination: "Sun-Earth L1",
    objective: "Sample particles from the Sun, the solar wind and the galaxy.",
    highlights: ["Its real-time solar wind data feeds NOAA space weather warnings."],
    url: sci("ace"),
    internal: { label: "Open Space Weather", to: "/weather" },
  },

  // ----------------------------- Earth science ---------------------------
  {
    id: "aqua",
    name: "Aqua",
    agency: "NASA Goddard",
    status: "extended",
    category: "earth",
    launched: "2002-05-04",
    launchLabel: "4 May 2002",
    vehicle: "Delta II",
    destination: "Sun-synchronous Earth orbit",
    objective: "Study Earth's water cycle: evaporation, clouds, precipitation, ice and snow.",
    highlights: ["Carries MODIS and AIRS, both widely used in weather and climate research."],
    url: sci("aqua"),
  },
  {
    id: "aura",
    name: "Aura",
    agency: "NASA Goddard",
    status: "extended",
    category: "earth",
    launched: "2004-07-15",
    launchLabel: "15 July 2004",
    vehicle: "Delta II",
    destination: "Sun-synchronous Earth orbit",
    objective: "Monitor ozone, air quality and atmospheric chemistry.",
    highlights: ["Its Ozone Monitoring Instrument tracks the ozone layer and pollution."],
    url: sci("aura"),
  },
  {
    id: "grace",
    name: "GRACE",
    agency: "NASA with DLR",
    status: "completed",
    category: "earth",
    launched: "2002-03-17",
    launchLabel: "17 March 2002",
    vehicle: "Rockot",
    destination: "Polar Earth orbit",
    objective: "Twin satellites mapping Earth's gravity field to track the movement of water and ice.",
    highlights: [
      "Measured mass loss of the Greenland and Antarctic ice sheets.",
      "Science mission ended in October 2017.",
    ],
    url: "https://grace.jpl.nasa.gov/",
    ended: "2017-10-27",
  },
  {
    id: "grace-fo",
    name: "GRACE-FO",
    agency: "NASA with GFZ",
    status: "active",
    category: "earth",
    launched: "2018-05-22",
    launchLabel: "22 May 2018",
    vehicle: "Falcon 9",
    destination: "Polar Earth orbit",
    objective: "Continue the GRACE gravity record and test laser ranging between satellites.",
    highlights: ["Carries the first laser ranging interferometer between spacecraft."],
    url: "https://gracefo.jpl.nasa.gov/",
  },
  {
    id: "smap",
    name: "SMAP",
    agency: "NASA JPL",
    status: "extended",
    category: "earth",
    launched: "2015-01-31",
    launchLabel: "31 January 2015",
    vehicle: "Delta II",
    destination: "Sun-synchronous Earth orbit",
    objective: "Measure soil moisture and whether soil is frozen or thawed, worldwide.",
    highlights: ["Maps global soil moisture every two to three days."],
    url: sci("smap"),
  },
  {
    id: "cygnss",
    name: "CYGNSS",
    agency: "NASA with University of Michigan",
    status: "extended",
    category: "earth",
    launched: "2016-12-15",
    launchLabel: "15 December 2016",
    vehicle: "Pegasus XL",
    destination: "Low Earth orbit",
    objective: "Eight small satellites measuring ocean surface winds inside hurricanes using GPS signals.",
    highlights: ["Sees winds through heavy rain that blocks other instruments."],
    url: sci("cygnss"),
  },
  {
    id: "sentinel-6",
    name: "Sentinel-6 Michael Freilich",
    agency: "NASA with ESA, EUMETSAT, NOAA and CNES",
    status: "active",
    category: "earth",
    launched: "2020-11-21",
    launchLabel: "21 November 2020",
    vehicle: "Falcon 9",
    destination: "Low Earth orbit",
    objective: "Measure global sea level with a radar altimeter, continuing a record begun in 1992.",
    highlights: ["Became the reference sea level satellite in 2022."],
    url: sci("sentinel-6"),
  },
  {
    id: "nisar",
    name: "NISAR",
    agency: "NASA with ISRO",
    status: "active",
    category: "earth",
    launched: "2025-07-30",
    launchLabel: "30 July 2025",
    vehicle: "GSLV-F16",
    destination: "Sun-synchronous Earth orbit",
    objective: "Radar mapping of Earth's land and ice surfaces to track earthquakes, volcanoes and ice sheets.",
    highlights: [
      "Carries two radars: NASA's L-band and ISRO's S-band.",
      "Its 12 m reflector is the largest NASA has flown on an Earth science satellite.",
    ],
    url: sci("nisar"),
  },
  {
    id: "landsat-8",
    name: "Landsat 8",
    agency: "NASA with USGS",
    status: "active",
    category: "earth",
    launched: "2013-02-11",
    launchLabel: "11 February 2013",
    vehicle: "Atlas V 401",
    destination: "Sun-synchronous Earth orbit",
    objective: "Continue the Landsat land imaging record that began in 1972.",
    highlights: ["Works with Landsat 9 to image the globe every eight days."],
    url: "https://landsat.gsfc.nasa.gov/satellites/landsat-8/",
  },
];
