/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EngineeringRouteImport } from './routes/engineering'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as AuthenticatedAcademyRouteImport } from './routes/_authenticated/academy'
import { Route as AuthenticatedAskRouteImport } from './routes/_authenticated/ask'
import { Route as AuthenticatedDeepspaceRouteImport } from './routes/_authenticated/deepspace'
import { Route as AuthenticatedIntelligenceRouteImport } from './routes/_authenticated/intelligence'
import { Route as AuthenticatedLaunchesRouteImport } from './routes/_authenticated/launches'
import { Route as AuthenticatedMarsRouteImport } from './routes/_authenticated/mars'
import { Route as AuthenticatedNeoRouteImport } from './routes/_authenticated/neo'
import { Route as AuthenticatedResearchRouteImport } from './routes/_authenticated/research'
import { Route as AuthenticatedResourcesRouteImport } from './routes/_authenticated/resources'
import { Route as AuthenticatedRomanRouteImport } from './routes/_authenticated/roman'
import { Route as AuthenticatedSkyRouteImport } from './routes/_authenticated/sky'
import { Route as AuthenticatedTrackerRouteImport } from './routes/_authenticated/tracker'
import { Route as AuthenticatedWeatherRouteImport } from './routes/_authenticated/weather'
import { Route as ApiAskRouteImport } from './routes/api/ask'
import { Route as ListShareIdRouteImport } from './routes/list.$shareId'
import { Route as AuthenticatedDeepspaceIndexRouteImport } from './routes/_authenticated/deepspace.index'
import { Route as AuthenticatedDeepspaceObjectIdRouteImport } from './routes/_authenticated/deepspace.$objectId'
import { Route as AuthenticatedTrackerIndexRouteImport } from './routes/_authenticated/tracker.index'
import { Route as AuthenticatedTrackerNoradIdRouteImport } from './routes/_authenticated/tracker.$noradId'
import { Route as ApiPublicRefreshNewsRouteImport } from './routes/api/public/refresh-news'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineeringRoute = EngineeringRouteImport.update({
  id: '/engineering',
  path: '/engineering',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAcademyRoute = AuthenticatedAcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAskRoute = AuthenticatedAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeepspaceRoute = AuthenticatedDeepspaceRouteImport.update({
  id: '/deepspace',
  path: '/deepspace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntelligenceRoute =
  AuthenticatedIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLaunchesRoute = AuthenticatedLaunchesRouteImport.update({
  id: '/launches',
  path: '/launches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarsRoute = AuthenticatedMarsRouteImport.update({
  id: '/mars',
  path: '/mars',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNeoRoute = AuthenticatedNeoRouteImport.update({
  id: '/neo',
  path: '/neo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResearchRoute = AuthenticatedResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRomanRoute = AuthenticatedRomanRouteImport.update({
  id: '/roman',
  path: '/roman',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkyRoute = AuthenticatedSkyRouteImport.update({
  id: '/sky',
  path: '/sky',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrackerRoute = AuthenticatedTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWeatherRoute = AuthenticatedWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAskRoute = ApiAskRouteImport.update({
  id: '/api/ask',
  path: '/api/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ListShareIdRoute = ListShareIdRouteImport.update({
  id: '/list/$shareId',
  path: '/list/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDeepspaceIndexRoute =
  AuthenticatedDeepspaceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDeepspaceRoute,
  } as any)
const AuthenticatedDeepspaceObjectIdRoute =
  AuthenticatedDeepspaceObjectIdRouteImport.update({
    id: '/$objectId',
    path: '/$objectId',
    getParentRoute: () => AuthenticatedDeepspaceRoute,
  } as any)
const AuthenticatedTrackerIndexRoute =
  AuthenticatedTrackerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTrackerRoute,
  } as any)
const AuthenticatedTrackerNoradIdRoute =
  AuthenticatedTrackerNoradIdRouteImport.update({
    id: '/$noradId',
    path: '/$noradId',
    getParentRoute: () => AuthenticatedTrackerRoute,
  } as any)
const ApiPublicRefreshNewsRoute = ApiPublicRefreshNewsRouteImport.update({
  id: '/api/public/refresh-news',
  path: '/api/public/refresh-news',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/engineering': typeof EngineeringRoute
  '/privacy': typeof PrivacyRoute
  '/about': typeof AuthenticatedAboutRoute
  '/academy': typeof AuthenticatedAcademyRoute
  '/ask': typeof AuthenticatedAskRoute
  '/deepspace': typeof AuthenticatedDeepspaceRouteWithChildren
  '/intelligence': typeof AuthenticatedIntelligenceRoute
  '/launches': typeof AuthenticatedLaunchesRoute
  '/mars': typeof AuthenticatedMarsRoute
  '/neo': typeof AuthenticatedNeoRoute
  '/research': typeof AuthenticatedResearchRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/roman': typeof AuthenticatedRomanRoute
  '/sky': typeof AuthenticatedSkyRoute
  '/tracker': typeof AuthenticatedTrackerRouteWithChildren
  '/weather': typeof AuthenticatedWeatherRoute
  '/api/ask': typeof ApiAskRoute
  '/list/$shareId': typeof ListShareIdRoute
  '/deepspace/$objectId': typeof AuthenticatedDeepspaceObjectIdRoute
  '/tracker/$noradId': typeof AuthenticatedTrackerNoradIdRoute
  '/api/public/refresh-news': typeof ApiPublicRefreshNewsRoute
  '/deepspace/': typeof AuthenticatedDeepspaceIndexRoute
  '/tracker/': typeof AuthenticatedTrackerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/engineering': typeof EngineeringRoute
  '/privacy': typeof PrivacyRoute
  '/about': typeof AuthenticatedAboutRoute
  '/academy': typeof AuthenticatedAcademyRoute
  '/ask': typeof AuthenticatedAskRoute
  '/intelligence': typeof AuthenticatedIntelligenceRoute
  '/launches': typeof AuthenticatedLaunchesRoute
  '/mars': typeof AuthenticatedMarsRoute
  '/neo': typeof AuthenticatedNeoRoute
  '/research': typeof AuthenticatedResearchRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/roman': typeof AuthenticatedRomanRoute
  '/sky': typeof AuthenticatedSkyRoute
  '/weather': typeof AuthenticatedWeatherRoute
  '/api/ask': typeof ApiAskRoute
  '/list/$shareId': typeof ListShareIdRoute
  '/deepspace/$objectId': typeof AuthenticatedDeepspaceObjectIdRoute
  '/tracker/$noradId': typeof AuthenticatedTrackerNoradIdRoute
  '/api/public/refresh-news': typeof ApiPublicRefreshNewsRoute
  '/deepspace': typeof AuthenticatedDeepspaceIndexRoute
  '/tracker': typeof AuthenticatedTrackerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/engineering': typeof EngineeringRoute
  '/privacy': typeof PrivacyRoute
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/academy': typeof AuthenticatedAcademyRoute
  '/_authenticated/ask': typeof AuthenticatedAskRoute
  '/_authenticated/deepspace': typeof AuthenticatedDeepspaceRouteWithChildren
  '/_authenticated/intelligence': typeof AuthenticatedIntelligenceRoute
  '/_authenticated/launches': typeof AuthenticatedLaunchesRoute
  '/_authenticated/mars': typeof AuthenticatedMarsRoute
  '/_authenticated/neo': typeof AuthenticatedNeoRoute
  '/_authenticated/research': typeof AuthenticatedResearchRoute
  '/_authenticated/resources': typeof AuthenticatedResourcesRoute
  '/_authenticated/roman': typeof AuthenticatedRomanRoute
  '/_authenticated/sky': typeof AuthenticatedSkyRoute
  '/_authenticated/tracker': typeof AuthenticatedTrackerRouteWithChildren
  '/_authenticated/weather': typeof AuthenticatedWeatherRoute
  '/api/ask': typeof ApiAskRoute
  '/list/$shareId': typeof ListShareIdRoute
  '/_authenticated/deepspace/$objectId': typeof AuthenticatedDeepspaceObjectIdRoute
  '/_authenticated/tracker/$noradId': typeof AuthenticatedTrackerNoradIdRoute
  '/api/public/refresh-news': typeof ApiPublicRefreshNewsRoute
  '/_authenticated/deepspace/': typeof AuthenticatedDeepspaceIndexRoute
  '/_authenticated/tracker/': typeof AuthenticatedTrackerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/engineering'
    | '/privacy'
    | '/about'
    | '/academy'
    | '/ask'
    | '/deepspace'
    | '/intelligence'
    | '/launches'
    | '/mars'
    | '/neo'
    | '/research'
    | '/resources'
    | '/roman'
    | '/sky'
    | '/tracker'
    | '/weather'
    | '/api/ask'
    | '/list/$shareId'
    | '/deepspace/$objectId'
    | '/tracker/$noradId'
    | '/api/public/refresh-news'
    | '/deepspace/'
    | '/tracker/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/engineering'
    | '/privacy'
    | '/about'
    | '/academy'
    | '/ask'
    | '/intelligence'
    | '/launches'
    | '/mars'
    | '/neo'
    | '/research'
    | '/resources'
    | '/roman'
    | '/sky'
    | '/weather'
    | '/api/ask'
    | '/list/$shareId'
    | '/deepspace/$objectId'
    | '/tracker/$noradId'
    | '/api/public/refresh-news'
    | '/deepspace'
    | '/tracker'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/engineering'
    | '/privacy'
    | '/_authenticated/about'
    | '/_authenticated/academy'
    | '/_authenticated/ask'
    | '/_authenticated/deepspace'
    | '/_authenticated/intelligence'
    | '/_authenticated/launches'
    | '/_authenticated/mars'
    | '/_authenticated/neo'
    | '/_authenticated/research'
    | '/_authenticated/resources'
    | '/_authenticated/roman'
    | '/_authenticated/sky'
    | '/_authenticated/tracker'
    | '/_authenticated/weather'
    | '/api/ask'
    | '/list/$shareId'
    | '/_authenticated/deepspace/$objectId'
    | '/_authenticated/tracker/$noradId'
    | '/api/public/refresh-news'
    | '/_authenticated/deepspace/'
    | '/_authenticated/tracker/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EngineeringRoute: typeof EngineeringRoute
  PrivacyRoute: typeof PrivacyRoute
  ApiAskRoute: typeof ApiAskRoute
  ListShareIdRoute: typeof ListShareIdRoute
  ApiPublicRefreshNewsRoute: typeof ApiPublicRefreshNewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineering': {
      id: '/engineering'
      path: '/engineering'
      fullPath: '/engineering'
      preLoaderRoute: typeof EngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academy': {
      id: '/_authenticated/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AuthenticatedAcademyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ask': {
      id: '/_authenticated/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AuthenticatedAskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deepspace': {
      id: '/_authenticated/deepspace'
      path: '/deepspace'
      fullPath: '/deepspace'
      preLoaderRoute: typeof AuthenticatedDeepspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intelligence': {
      id: '/_authenticated/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof AuthenticatedIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/launches': {
      id: '/_authenticated/launches'
      path: '/launches'
      fullPath: '/launches'
      preLoaderRoute: typeof AuthenticatedLaunchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mars': {
      id: '/_authenticated/mars'
      path: '/mars'
      fullPath: '/mars'
      preLoaderRoute: typeof AuthenticatedMarsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/neo': {
      id: '/_authenticated/neo'
      path: '/neo'
      fullPath: '/neo'
      preLoaderRoute: typeof AuthenticatedNeoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/research': {
      id: '/_authenticated/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof AuthenticatedResearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resources': {
      id: '/_authenticated/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roman': {
      id: '/_authenticated/roman'
      path: '/roman'
      fullPath: '/roman'
      preLoaderRoute: typeof AuthenticatedRomanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sky': {
      id: '/_authenticated/sky'
      path: '/sky'
      fullPath: '/sky'
      preLoaderRoute: typeof AuthenticatedSkyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tracker': {
      id: '/_authenticated/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof AuthenticatedTrackerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/weather': {
      id: '/_authenticated/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof AuthenticatedWeatherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/ask': {
      id: '/api/ask'
      path: '/api/ask'
      fullPath: '/api/ask'
      preLoaderRoute: typeof ApiAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/$shareId': {
      id: '/list/$shareId'
      path: '/list/$shareId'
      fullPath: '/list/$shareId'
      preLoaderRoute: typeof ListShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/deepspace/': {
      id: '/_authenticated/deepspace/'
      path: '/'
      fullPath: '/deepspace/'
      preLoaderRoute: typeof AuthenticatedDeepspaceIndexRouteImport
      parentRoute: typeof AuthenticatedDeepspaceRoute
    }
    '/_authenticated/deepspace/$objectId': {
      id: '/_authenticated/deepspace/$objectId'
      path: '/$objectId'
      fullPath: '/deepspace/$objectId'
      preLoaderRoute: typeof AuthenticatedDeepspaceObjectIdRouteImport
      parentRoute: typeof AuthenticatedDeepspaceRoute
    }
    '/_authenticated/tracker/': {
      id: '/_authenticated/tracker/'
      path: '/'
      fullPath: '/tracker/'
      preLoaderRoute: typeof AuthenticatedTrackerIndexRouteImport
      parentRoute: typeof AuthenticatedTrackerRoute
    }
    '/_authenticated/tracker/$noradId': {
      id: '/_authenticated/tracker/$noradId'
      path: '/$noradId'
      fullPath: '/tracker/$noradId'
      preLoaderRoute: typeof AuthenticatedTrackerNoradIdRouteImport
      parentRoute: typeof AuthenticatedTrackerRoute
    }
    '/api/public/refresh-news': {
      id: '/api/public/refresh-news'
      path: '/api/public/refresh-news'
      fullPath: '/api/public/refresh-news'
      preLoaderRoute: typeof ApiPublicRefreshNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDeepspaceRouteChildren {
  AuthenticatedDeepspaceObjectIdRoute: typeof AuthenticatedDeepspaceObjectIdRoute
  AuthenticatedDeepspaceIndexRoute: typeof AuthenticatedDeepspaceIndexRoute
}

const AuthenticatedDeepspaceRouteChildren: AuthenticatedDeepspaceRouteChildren =
  {
    AuthenticatedDeepspaceObjectIdRoute: AuthenticatedDeepspaceObjectIdRoute,
    AuthenticatedDeepspaceIndexRoute: AuthenticatedDeepspaceIndexRoute,
  }

const AuthenticatedDeepspaceRouteWithChildren =
  AuthenticatedDeepspaceRoute._addFileChildren(
    AuthenticatedDeepspaceRouteChildren,
  )

interface AuthenticatedTrackerRouteChildren {
  AuthenticatedTrackerNoradIdRoute: typeof AuthenticatedTrackerNoradIdRoute
  AuthenticatedTrackerIndexRoute: typeof AuthenticatedTrackerIndexRoute
}

const AuthenticatedTrackerRouteChildren: AuthenticatedTrackerRouteChildren = {
  AuthenticatedTrackerNoradIdRoute: AuthenticatedTrackerNoradIdRoute,
  AuthenticatedTrackerIndexRoute: AuthenticatedTrackerIndexRoute,
}

const AuthenticatedTrackerRouteWithChildren =
  AuthenticatedTrackerRoute._addFileChildren(AuthenticatedTrackerRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedAcademyRoute: typeof AuthenticatedAcademyRoute
  AuthenticatedAskRoute: typeof AuthenticatedAskRoute
  AuthenticatedDeepspaceRoute: typeof AuthenticatedDeepspaceRouteWithChildren
  AuthenticatedIntelligenceRoute: typeof AuthenticatedIntelligenceRoute
  AuthenticatedLaunchesRoute: typeof AuthenticatedLaunchesRoute
  AuthenticatedMarsRoute: typeof AuthenticatedMarsRoute
  AuthenticatedNeoRoute: typeof AuthenticatedNeoRoute
  AuthenticatedResearchRoute: typeof AuthenticatedResearchRoute
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRoute
  AuthenticatedRomanRoute: typeof AuthenticatedRomanRoute
  AuthenticatedSkyRoute: typeof AuthenticatedSkyRoute
  AuthenticatedTrackerRoute: typeof AuthenticatedTrackerRouteWithChildren
  AuthenticatedWeatherRoute: typeof AuthenticatedWeatherRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedAcademyRoute: AuthenticatedAcademyRoute,
  AuthenticatedAskRoute: AuthenticatedAskRoute,
  AuthenticatedDeepspaceRoute: AuthenticatedDeepspaceRouteWithChildren,
  AuthenticatedIntelligenceRoute: AuthenticatedIntelligenceRoute,
  AuthenticatedLaunchesRoute: AuthenticatedLaunchesRoute,
  AuthenticatedMarsRoute: AuthenticatedMarsRoute,
  AuthenticatedNeoRoute: AuthenticatedNeoRoute,
  AuthenticatedResearchRoute: AuthenticatedResearchRoute,
  AuthenticatedResourcesRoute: AuthenticatedResourcesRoute,
  AuthenticatedRomanRoute: AuthenticatedRomanRoute,
  AuthenticatedSkyRoute: AuthenticatedSkyRoute,
  AuthenticatedTrackerRoute: AuthenticatedTrackerRouteWithChildren,
  AuthenticatedWeatherRoute: AuthenticatedWeatherRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EngineeringRoute: EngineeringRoute,
  PrivacyRoute: PrivacyRoute,
  ApiAskRoute: ApiAskRoute,
  ListShareIdRoute: ListShareIdRoute,
  ApiPublicRefreshNewsRoute: ApiPublicRefreshNewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
